const TranslateText = {
    ua: {
        header: {
            menu: {
                shop: "Магазин",
                bag: "Сумки",
                backpack: "Рюкзаки",
                wallets: "Гаманці",
                brand: "Бренди",
                about: "Про нас",
                contacts: "Контакти",
            },
            work: {
                head: "Графік роботи",
                time: "пн-сб: 10:00 - 20:00",
                holiday: "нд: Вихідний",
            },
        },
        main: {
            bag: "Сумки",
            backpack: "Рюкзаки",
            wallets: "Гаманці",
        },
        contacts: {
            contactHead: "Контактна інформація",
            cbHead: "Зворотній зв’язок",
            inputs: {
                name: "Ваше ім’я",
                mail: "Пошта",
                tel: "Номер телефону",
                msg: "Ваше повідомлення",
                btn: "Відправити",
            },
        },
        footer: {
            return: "Обмін та повернення",
            terms: "Положення та умови",
            delivery: "Перевезення та доставка",
            contacts: "Контакти",
        },
        products: {
            filters: {
                price: "Ціна",
                brand: "Бренди",
                from: "від",
                to: "до",
            },
            btn: "Фільтри",
        },
        cart: {
            btnBuy: "Оформити замовлення",
            btnMore: "Оновити кошик",
            total: "Разом",
        },
        userCart: {
            header: "Особиста інформація",
            name: "Ім'я",
            secondname: "Прізвище",
            phone: "Телефон",
            address: "Адреса",
            deliveryMethod: "Метод доставки",
            courier: "Кур'єр",
            np: "Нова Пошта",
            own: "Самовивіз",
            payMethod: "Метод оплати",
            card: "Карта",
            ondelivery: "При отриманні",
            btn: "Підтвердити замовлення",
            alerts: {
                ok: "Ваше замовлення прийняте в обробку! спасибі",
                orderId: "Ваш номер замовлення: ",
                warn: "Щось пішло не так",
                error: "Помилка із створенням замовлення. Зателефонуйте для замовлення",
                cardError: "Оплата карткою не доступна",
                name: "Ім'я не вказано",
                secName: "Прізвище не вказане",
                address: "Телефон не вказано",
                phone: "Адреса не вказана",
            },
        },
        successPage: {
            head: "Дякуємо!",
            ok: "Ваше замовлення прийнято!",
        },
    },

    ru: {
        header: {
            menu: {
                shop: "Магазин",
                bag: "Сумки",
                backpack: "Рюкзаки",
                wallets: "Кошельки",
                brand: "Бренды",
                about: "О нас",
                contacts: "Контакты",
            },
            work: {
                head: "График работы",
                time: "пн-сб: 10:00 - 20:00",
                holiday: "вс: Выходной",
            },
        },
        main: {
            bag: "Сумки",
            backpack: "Рюкзаки",
            wallets: "Кошельки",
        },
        contacts: {
            contactHead: "Контактная информация",
            cbHead: "Обратная связь",
            inputs: {
                name: "Ваше имя",
                mail: "Почта",
                tel: "Номер телефона",
                msg: "Ваше сообщение",
                btn: "Отправить",
            },
        },
        footer: {
            return: "Обмен и возврат",
            terms: "Положения и условия",
            delivery: "Перевозки и доставка",
            contacts: "Контакты",
        },
        products: {
            filters: {
                price: "Цены",
                brand: "Бренды",
                from: "от",
                to: "до",
            },
            btn: "Фильтры",
        },
        cart: {
            btnBuy: "Оформить заказ",
            btnMore: "Обновить корзину",
            total: "Вместе",
        },
        userCart: {
            header: "Личная информация",
            name: "Имя",
            secondname: "Фамилия",
            phone: "Телефон",
            address: "Адрес",
            deliveryMethod: "Метод Доставки",
            courier: "Курьер",
            np: "Нова Почта",
            own: "Самовывоз",
            payMethod: "Метод Оплаты",
            card: "Карта",
            ondelivery: "При получении",
            btn: "Подтвердить заказ",
            alerts: {
                ok: "Ваш заказ принят в обработку! Спасибо",
                orderId: "Ваш номер заказа: ",
                warn: "Что то пошло не так",
                error: "Ошибка с созданием заказа. Позвоните для заказа",
                cardError: "Оплата картой не доступна",
                name: "Имя не указано",
                secName: "Фамилия не указана",
                address: "Телефон не указано",
                phone: "Адрес не указан",
            },
        },
        successPage: {
            head: "Спасибо!",
            ok: "Ваш заказ принят!",
        },
    },
};

export default TranslateText;
